name        'drush'
version     '0.0.1'
source      'https://github.com/jvc26/puppet-drush.git'
license     'Apache License, Version 2.0'
summary     'drush module for Puppet'
description 'Puppet module enabling the installation and setup of Drush'
